### PR TITLE
Chacha20 Initial Implementation

### PR DESCRIPTION
**Pull request by docandrew**
Here's an initial take on a ChaCha20 implementation w/ the IETF key setup as well. It's basically a translation of the "merged" reference implementation from https://cr.yp.to/streamciphers/timings/estreambench/submissions/salsa20/chacha8/merged/chacha.c. 

I added a test case, `stream5.adb` which uses the test vector in RFC 8439. I was able to discharge subprogram proofs just using the "fast" SPARK mode/Z3. I think it _mostly_ matches the package layout used for Salsa20, with the "meat" of the algorithm in SPARKNaCl.Core and public-facing functions in SPARKNaCl.Stream.

This does _not_ yet implement the full AEAD ChaCha20_Poly1305_SHA256 cipher, only the ChaCha20 stream algorithm itself.

I'm sure there's plenty of room for improvement, but I think it's at a place where some outside feedback is warranted - please let me know what you think!

### CODE REVIEW

**Comment by rod-chapman** [comment]
I have added some more test cases from Appendix A of the RFC.

**Comment by rod-chapman** [comment]
Also looking at refactoring Core.ChaCha20_Encrypt_Bytes to be able to prove the correct initialisation of C.
This is proving a little bit tricky so far...

**Comment by docandrew** [comment]
Wondering if maybe the solution is to get rid of the B < 64 and Tmp array business, and break out a second loop for the last partial block, kind of like you have in Salsa20_Xor_Local?

**Comment by rod-chapman** [comment]
Working on it now... I have to go do childcare stuff in about 30 minutes, so I will commit what I have before then.

**Comment by rod-chapman** [comment]
OK... I Pushed. Not proving OK yet, but see what you think...

**Comment by docandrew** [comment]
Seems like a good way forward! I've pulled your changes and will see if I can figure it out - I think maybe proving the 'Initialized assert in that third case (more than 64 bytes remaining) might do the trick.

**Comment by docandrew** [comment]
Getting closer... Not sure what to do about the range check in the ChaCha_Encrypt_Bytes precondition (C'Length <= N32'Last) though. Any ideas?

**Comment by docandrew** [comment]
OK, I think it's in good shape proof-wise now. If this looks good to you I'll take a look at the SHA256 work.

**Comment by rod-chapman** [comment]
OK... looks good. I have reproduced proof here using both SPARK Community 2021 and SPARK Pro 22.1 and all is well.

**Pull request merged**
