### PR TITLE
HMAC, HKDF and ChaCha20

### PR DESCRIPTION
**Pull request by docandrew**
I think I was able to address most of your suggestions from the last PR. This includes a significant increase in the number of test cases for SHA-256, HMAC and HKDF as well. The biggest change from when you looked previously will be the HKDF Expand implementation. Feedback always welcome!

### CODE REVIEW

**Comment by rod-chapman** [comment]
Looking at the extra tests for SHA256 - where is the source of these? The FIPS 180-4 document no longer seems to include test vectors. Is there an extra document or link that we could reference?

**Comment by rod-chapman** [comment]
The new HKDF code was confusing me a bit, but I see why. In the rest of the code, array subtypes that end with a literal number are always constrained (e.g. "Bytes_32" is a constrained 32-byte subtype of Byte_Seq) and Unconstrained array types end in "Seq".  Your naming of "OKM_Index_256" and "OKM_256" doesn't follow that convention, so was confusing me. I think they should be "OKM_Index" and "OKM_Seq" respectively so it's more obvious that the OKM "out" parameter is unconstrained. I can see a few other potential implications as well. I will implement these, re-prove and test here this morning...

**Comment by rod-chapman** [comment]
OK... proof and test results all looking good here with SPARK Community 2021. One comment above on the "Counter" parameter to AEAD Create procedure...

**Comment by docandrew** [comment]
The extra SHA-256 test cases came from NIST at https://csrc.nist.gov/Projects/Cryptographic-Algorithm-Validation-Program/Secure-Hashing, using the byte-oriented test vectors. 

With the OKM type naming I was hoping to leave room for SHA-512 implementations of HMAC and HKDF at some point, kind of like Digest_256 and Digest_512. TLS 1.3 doesn’t use them in it’s cipher suites but future specs might. 

Ideally though, HMAC and HKDF would be able to use any underlying hash algorithm, so could be implemented as generics in the future.

**Comment by rod-chapman** [comment]
OK... can you add a comment point at the source of those test cases?

I think we should leave OKM_Seq as an unconstrained type. We might have to increase its range in future, but then add specific constraints for each version via preconditions?

Agree - generics is the way to go for generalising over hash algorithms and so on.

**Comment by rod-chapman** [comment]
OK... looks good - shall we go for a merge?

**Comment by docandrew** [comment]
Phew, no pressure :) Using the updates I'm still able to do key exchange with the OpenSSL server, so I think we're in good shape.

**Comment by docandrew** [comment]
I'm really impressed by the HKDF.Expand cleanup you did, BTW - it's much cleaner now.

**Comment by rod-chapman** [comment]
OK... I will try for a "squash and merge" this morning. I will also then attempt a catchup merge from master onto my "new_mul" branch so it's up to date...

**Pull request merged**
